name: nodesite

on: push


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v2

    - name : echo test
      run : echo "hello"

    - name : install dependencies
      run : sudo apt install npm

 
    
      
  
